# Generated by Django 5.2.3 on 2025-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikephoto',
            name='estimated_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bikephoto',
            name='predicted_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
